spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/study/urlShortener
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        #format_sql: true
    #database-platform: org.hibernate.dialect

logging.level:
  org.hibernate.SQL: debug
  #org.springframework: debug
#  org.hibernate.type: trace